import Team from "./Team/Team";
import HomePage from "./HomePage/HomePage";
// import Newsletter from "./Newsletter/Newsletter";
import Gallery from "./Gallery/Gallery";
import Events from "./Events/Events";
import NotableAlumni from "./NotableAlumni/NotableAlumni";
// import News from "./Newsletter/News";
import AlumniCorner from "./AlumniCorner/AlumniCorner";
import Donate from "./Donate/Donate";
import Resources from "./Resources/Resources";
import Interaction from "./Interaction/Interaction";
import About from "./About/About";
import TeamCard from "./Team/TeamCard";
import TeamCard2 from "./Team/TeamCard2";
// import NewsId from "./Newsletter/NewsId";
// import Blog from "./AlumniCorner/Blog";
import Blogs from "./Blogs/Blogs";
import BihtaCampus from "./Bihta-Campus/BihtaCampus";
import Error from "./Error/Error";
import AlumniDatabase from "./AlumniDatabase/AlumniDatabase";
import History from "./History/History"
import JobOffers from "./JobOffers/JobOffers";
import SuccessStories from "./SuccessStories/SuccessStories";
import PreviousMeets from "./AlumniMeet/PreviousMeets";
import Experiences from "./Experiences/Experiences";
import Experience from "./Experiences/Experience";

import SignIn from "./Auth/SignIn";
import SignUp from "./Auth/SignUp";
import Verify from "./Auth/Verify";
import ForgotPassword from "./Auth/ForgotPassword";
import ResetPassword from "./Auth/ResetPassword";
import Dashboard from "./ProtectedPages/Dashboard";
import Profile from "./ProtectedPages/Profile/Profile";
import AlumniProfile from "./ProtectedPages/AlumniProfile/AlumniProfile";
import GiveTestimonial from "./ProtectedPages/GiveTestimonial/GiveTestimonial";
import PostInernship from "./ProtectedPages/PostInternship/PostInternship";
import PostJob from "./ProtectedPages/PostJob/PostJob";
import ShareExperience from "./ProtectedPages/ShareExperience/ShareExperience";
import WriteBlog from "./ProtectedPages/WriteBlog/WriteBlog";
import ReportBug from "./ProtectedPages/ReportBug/ReportBug";
import VerifyEmail from "./Auth/VerifyEmail";

export { Team, HomePage, Gallery, Events, NotableAlumni, AlumniCorner, Donate, Resources, Interaction, About, TeamCard, TeamCard2, Blogs, BihtaCampus, Error, AlumniDatabase, History, JobOffers, SuccessStories, PreviousMeets, SignIn, SignUp, Verify, ForgotPassword, ResetPassword, Profile, AlumniProfile, GiveTestimonial, PostInernship, PostJob, ShareExperience, WriteBlog, Dashboard, ReportBug, Experiences, Experience, VerifyEmail };
